//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDM.Portal.PortalAppWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string User { get; set; }
        public string Password { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public string Schedule { get; set; }
        public Nullable<System.DateTime> LastCrawled { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public bool Enable { get; set; }
        public string Description { get; set; }
    
        public virtual SourceType SourceType { get; set; }
    }
}
