//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDM.Portal.PortalAppWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceType
    {
        public SourceType()
        {
            this.Sources = new HashSet<Source>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Assembly { get; set; }
        public string Class { get; set; }
    
        public virtual ICollection<Source> Sources { get; set; }
    }
}
